mosip/mosip-infra

- deployment/sandbox-v2/roles/postgres/tasks/init_db.yml
Minor changes w.r.t postgres installation.
> [MOSIP-257] Base path added

- deployment/sandbox-v2/roles/nginx/templates/nginx_https_conf.yml.j2
> [MOSIP-8035] proxy_header_set config in nginx reverted back as swagger

- deployment/sandbox-v2/README.md
- deployment/sandbox-v2/docs/mosip_configuration_guide.md
- deployment/sandbox-v2/group_vars/all.yml
- deployment/sandbox-v2/helm/charts/postgres/templates/pg-dep.yaml
- deployment/sandbox-v2/helm/charts/postgres/values.template.j2
- deployment/sandbox-v2/playbooks/mzcluster.yml
- deployment/sandbox-v2/roles/config-repo/files/properties/application-mz.properties
- deployment/sandbox-v2/roles/config-repo/files/properties/kernel-mz.properties
- deployment/sandbox-v2/roles/config-repo/files/properties/pre-registration-mz.properties
- deployment/sandbox-v2/terraform/aws/sandbox/README.md
> [MOSIP-1806] Taint and affinity added for Postgres.

- deployment/sandbox-v2/playbooks/postgres.yml
- deployment/sandbox-v2/roles/config-repo/files/properties/registration-processor-mz.properties
- deployment/sandbox-v2/terraform/aws/sandbox/README.md
> force_init option added in postgres install.

- deployment/sandbox-v2/roles/keycloak-init/defaults/main.yml
added new roles for regproc-client
> added new roles for regproc-client

- deployment/sandbox-v2/group_vars/all.yml
- deployment/sandbox-v2/helm/charts/elasticsearch/.gitignore
- deployment/sandbox-v2/helm/charts/elasticsearch/templates/statefulset.yaml
- deployment/sandbox-v2/helm/charts/elasticsearch/values.template.j2
- deployment/sandbox-v2/helm/charts/nfs-client-provisioner/.gitignore
- deployment/sandbox-v2/helm/charts/nfs-client-provisioner/values.template.j2
- deployment/sandbox-v2/playbooks/elasticsearch.yml
- deployment/sandbox-v2/playbooks/nfs-provisioner.yml
- deployment/sandbox-v2/playbooks/reset/reset-monitoring.yml
- deployment/sandbox-v2/roles/keycloak-init/defaults/main.yml
- deployment/sandbox-v2/site.yml
> MOSIP-9702 Persistence added to Elasticsearch

- deployment/sandbox-v2/group_vars/all.yml
- deployment/sandbox-v2/helm/charts/kernel/templates/key-dep.yaml
- deployment/sandbox-v2/helm/charts/kernel/templates/keys-job.yaml
- deployment/sandbox-v2/helm/charts/kernel/values.template.j2
Added runtime env variable for HSM client zip path
> Added runtime env variable for hsm client zip path

- deployment/sandbox-v2/helm/charts/ida/templates/auth-dep.yaml
- deployment/sandbox-v2/helm/charts/ida/templates/internal-dep.yaml
- deployment/sandbox-v2/helm/charts/ida/templates/keys-job.yaml
- deployment/sandbox-v2/helm/charts/ida/templates/kyc-dep.yaml
- deployment/sandbox-v2/helm/charts/ida/templates/otp-dep.yaml
- deployment/sandbox-v2/helm/charts/ida/values.template.j2
Soft HSM to Real HSM Switch IDA
> Soft HSM to Real HSM Switch IDA

- deployment/sandbox-v2/utils/onboard/ida_zk/api.py
- deployment/sandbox-v2/utils/onboard/ida_zk/ida_zk.py
One more cert upload added that's required for IDA.
> [MOSIP-10061] Cert added. 

- deployment/sandbox-v2/roles/keycloak-init/defaults/main.yml
New role added to manage the misp partner
> MISP_Partner role added

- deployment/sandbox-v2/group_vars/all.yml
- deployment/sandbox-v2/helm/charts/dmzregproc/values.template.j2
- deployment/sandbox-v2/helm/charts/kafka/.gitignore
- deployment/sandbox-v2/helm/charts/kafka/values.template.j2
- deployment/sandbox-v2/helm/charts/regproc/values.template.j2
- deployment/sandbox-v2/playbooks/dmzkafka.yml
- deployment/sandbox-v2/playbooks/mzkafka.yml
- deployment/sandbox-v2/playbooks/reset/reset-kafka.yml
- deployment/sandbox-v2/reset.yml
- deployment/sandbox-v2/roles/packages/helm-cli/tasks/main.yml
- deployment/sandbox-v2/site.yml
Kafka cluster helm chart added with respective config to sandbox
> MOSIP-10835 : Kafka cluster helm chart added with respective config to sandbox

- deployment/sandbox-v2/docs/k8s_master_ha.md
Currently we have a setup where the number of master node is only one. This is not the good way because if  the master goes down the whole cluster will be down. So here is the need of setup with multiple master nodes available so in case there is some issue with the master the next master node can take its place and the cluster will be regain its state.
> [MOSIP-11045] Creation of High Availability Master Setup

- deployment/sandbox-v2/playbooks/console.yml
check all the cluster nodes are accessible from the console before you begin
> check nodes are accessible from the console 

- deployment/sandbox-v2/group_vars/all.yml
Adding comments and sample attributes for required fields.
> [MOSIP-11528] Resolving Alerts using Prometheus Alert Manager

- deployment/sandbox-v2/helm/charts/datashare/templates/datashare-dep.yaml
- deployment/sandbox-v2/helm/charts/datashare/values.template.j2
- deployment/sandbox-v2/versions.yml
> [MOSIP-11903] Datashare and bio-dedup upgraded to 1.1.4

- deployment/sandbox-v2/roles/keycloak-init/defaults/main.yml
In keycloak new client has been added. This is for PMS UI.
> mosip-pms-clinet

- deployment/sandbox-v2/helm/charts/regproc/templates/reprocess-dep.yaml
- deployment/sandbox-v2/helm/charts/regproc/templates/reprocess-svc.yaml
- deployment/sandbox-v2/helm/charts/regproc/values.template.j2
- deployment/sandbox-v2/roles/nginx/templates/nginx_https_conf.yml.j2
This is for pause and resume story
> MOSIP-12616 : New ports and URL pattern of reprocessor stage exposed

- deployment/sandbox-v2/helm/charts/admin/templates/ui-dep.yaml
- deployment/sandbox-v2/helm/charts/pms/values.template.j2
- deployment/sandbox-v2/helm/charts/regproc/templates/salt-job.yaml
- deployment/sandbox-v2/helm/charts/regproc/values.template.j2
- deployment/sandbox-v2/roles/nginx/templates/nginx_index.yml.j2
Removed regproc salt generator table name. Table not exists.
added regclient test utility link in nginex
> Changed url for pmp config.json.

- deployment/sandbox-v2/group_vars/all.yml
- deployment/sandbox-v2/roles/functional-test-run/tasks/main.yml
- deployment/sandbox-v2/roles/packages/openjdk/tasks/main.yml
added variable for mosip functional test
> added utils_dir variable for funtional_test purpose

- deployment/sandbox-v2/helm/charts/ida/templates/auth-dep.yaml
- deployment/sandbox-v2/helm/charts/ida/templates/otp-dep.yaml
> [ DSD-571 ] added iam_adapter_url_env for ida deployment 

- build/file-server/default.conf
> Revert "updated nginx port & path in default.conf"

- deployment/sandbox-v2/group_vars/all.yml
- deployment/sandbox-v2/roles/mosip-file-server/tasks/main.yml
Added new path for nginx service.
> Updated files server chart fro new apk deployment.

- deployment/sandbox-v2/roles/keycloak-init/files/realms/realm_mosip.json
so a client has 1 minute to finish access token protocol.Also 1 minute is the standard recommended time period.
> accesscodelifespan is 1 min now.

- deployment/sandbox-v2/versions.yml
updated docker images to mosipqa
> [ MOSIP-21127 ] updated versions.yml file

- deployment/sandbox-v2/podconfig.yml
> [ MOSIP-21222 ] versions.yml

- deployment/v3/mosip/all/delete-all.sh
As this has been added to resident
> removed resident-app

- deployment/v3/mosip/compliance-toolkit/install.sh
> [MOSIP-21791] created deployment script for mosip-compliance-toolkit.

- deployment/sandbox-v2/docs/idacert.md
Added steps for uploading CA and Sub-CA certs
> Added steps for uploading CA and Sub-CA certs

- deployment/v3/external/iam/import-init-values.yaml
remove sa roles from mosip-prereg-client
> [ MOSIP-23511 ] updated import-init-values.yaml

- deployment/v3/mosip/idrepo/copy_cm.sh
- deployment/v3/mosip/idrepo/install.sh
- deployment/v3/mosip/kernel/copy_cm.sh
- deployment/v3/mosip/kernel/install.sh
- deployment/v3/mosip/pms/copy_cm.sh
- deployment/v3/mosip/pms/install.sh
- deployment/v3/mosip/resident/copy_cm.sh
- deployment/v3/mosip/resident/install.sh
> [ DSD-1944 ] removed artifactory-share-develop from install.sh and copy_cm.sh

- deployment/v3/mosip/apitestrig/values.yaml
updated apitesyrig values.yaml from idp to esignet
> DSD-2510 module name changed from idp to esignet

- deployment/v3/external/kafka/README.md
- deployment/v3/external/kafka/backup.sh
- deployment/v3/external/kafka/restore.sh
* [MOSIP-28014] updated kafka backup and restore script
* [MOSIP-28014] updated kafka backup README.md
---------
[MOSIP-28014]: https://mosip.atlassian.net/browse/MOSIP-28014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOSIP-28014]: https://mosip.atlassian.net/browse/MOSIP-28014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOSIP-28014] updated kafka backup and restore script (#1364)

- deployment/v3/external/msg-gateway/README.md
- deployment/v3/external/msg-gateway/install.sh
- deployment/v3/mosip/config-server/copy_cm.sh
- deployment/v3/mosip/config-server/copy_secrets.sh
- deployment/v3/mosip/config-server/delete.sh
- deployment/v3/mosip/mock-smtp/README.md
* [DSD-2651]added sms and email configuration
* [DSD-2651]replaced sms with email
* [DSD-2651]replaced sms with email
* [DSD-2651]replaced sms with email
* [DSD-2651]replaced sms with email
* [DSD-2651]replaced sms with email
* [DSD-2651]
* [DSD-2651] updated the README.md
* [DSD-2651] updated the README.md
* [DSD-2651] updated the README.md
* [DSD-2651] updated the sms
* [DSD-2651] updated the sms
* [DSD-2651] updated the sms
* [DSD-2651] updated the README.md
* [DSD-2651] updated the README.md
* [DSD-2651] updated the README.md
* [DSD-2651] updated the README.md
* [DSD-2651] updated the README.md
* [DSD-2651] updated the README.md
---------
[DSD-2651]: https://mosip.atlassian.net/browse/DSD-2651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [DSD-2651]cherry-picked the commit from develop

- deployment/v3/mosip/image-compressor/README.md
- deployment/v3/mosip/image-compressor/copy_cm.sh
- deployment/v3/mosip/image-compressor/delete.sh
- deployment/v3/mosip/image-compressor/install.sh
* [DSD-3438] Updated install.sh
* [DSD-3532] added imagecompressor installation script
* [DSD-3532] updated install.sh
---------
[DSD-3438]: https://mosip.atlassian.net/browse/DSD-3438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DSD-3532]: https://mosip.atlassian.net/browse/DSD-3532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DSD-3532]: https://mosip.atlassian.net/browse/DSD-3532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DSD-3532] added imagecompressor installation script (#1433)

- deployment/v3/testrig/apitestrig/install.sh
…r slack channel in install script
> [DSD-4730] Added slack webhook URL to notify server end issues on your slack channel in install script

- deployment/v3/external/iam/chart/istio-addons/templates/virtualservice.yaml
> [MOSIP-36541] Update the virtual service to take HTTP route based on the service name.
